<a href="https://colab.research.google.com/github/ayts9806/class2021Spring/blob/main/20210426.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%matplotlib inline
from matplotlib import pyplot as plt
import IPython.display as ipd
import numpy as np
from scipy.signal import lfilter

In [9]:
def phasor(amp, sr, dur, freq):
  t = np.arange(1, sr*dur+1)/sr
  theta = t * 2*np.pi * freq
  s = np.sin(theta)
  return s, theta, t

In [10]:
phasor(10,10000,1,200)

(array([ 1.25333234e-01,  2.48689887e-01,  3.68124553e-01, ...,
        -2.48689887e-01, -1.25333234e-01,  7.85754689e-15]),
 array([1.25663706e-01, 2.51327412e-01, 3.76991118e-01, ...,
        1.25638573e+03, 1.25651140e+03, 1.25663706e+03]),
 array([1.000e-04, 2.000e-04, 3.000e-04, ..., 9.998e-01, 9.999e-01,
        1.000e+00]))